import { Inter } from 'next/font/google'
import { OrdersProvider } from '@/context/OrdersContext'
import NavBar from '@/components/navbar'
import Providers from './Provider'
import './globals.css'
import Space from '@/components/space'

const inter = Inter({
    subsets: ['latin']
})

export const metadata = {
    title: 'Majestic Food',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="es" className='font-mono'>
            <body className={inter.className}>
                <main className="flex min-h-screen flex-col relative">
                        <OrdersProvider>
                            <Providers>
                                <NavBar />
                                <Space />
                                {children}
                            </Providers>
                        </OrdersProvider>
                </main>
            </body>
        </html>
    )
}
